---
# Status Binary Sensor
#
# The Status Binary Sensor exposes the node state (if itâ€™s connected to via MQTT/native API) for Home Assistant.
#
# https://esphome.io/components/binary_sensor/status/
#
binary_sensor:
  - platform: status
    id: esphome_status
    name: "Online"
