---
# SNTP Time Source
#
# A way to get time in ESPHome is using SNTP. It will
# be used to periodically synchronize the current time.
#
# https://esphome.io/components/time.html#sntp-time-source
#
platform: sntp
id: time_sntp
servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
on_time:
  - seconds: 0
    minutes: 0
    hours: 0
    then:
      - lambda: |-
          id(daily_reset) = true;