---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#
platform: wifi_info
ip_address:
  name: "WiFi IP Address"
  id: sensor_ip_address
  entity_category: "diagnostic"
ssid:
  name: "WiFi SSID"
  id: sensor_ssid
  entity_category: "diagnostic"
bssid:
  name: "WiFi BSSID"
  id: sensor_bssid
  entity_category: "diagnostic"
mac_address:
  name: "WiFi MAC Address"
  id: sensor_mac_address
  entity_category: "diagnostic"
