---
# Native API component
#
# The ESPHome native API is used to communicate with clients directly, with a
# highly-optimized network protocol. Currently, only the ESPHome tool and
# Home Assistant use this native API.
#
# https://esphome.io/components/api.html
#
substitutions:
  api_key: !secret esphome_api_encryptionKey

api:
  encryption:
    key: "${api_key}"
  reboot_timeout: 30min