---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Lisbon"

globals:
  - { id: daily_reset, type: bool, restore_value: false, initial_value: 'false' }

time:
  - <<: !include ../sensors/time/homeassistant.yaml
    timezone: "${time_timezone}"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - <<: !include ../sensors/time/sntp.yaml
    timezone: "${time_timezone}"

sensor:
  - <<: !include ../sensors/uptime.yaml
  - <<: !include ../sensors/uptime_timestamp.yaml
