---
# WiFi Signal Sensor
#
# The wifi_signal sensor platform allows you to read the signal strength of the
# currently connected WiFi Access Point.
#
# https://esphome.io/components/sensor/wifi_signal.html
#
platform: wifi_signal
name: "WiFi Signal dB"
id: wifi_signal_db
update_interval: 60s
entity_category: "diagnostic"
